// Auto-generated by gen_config.py

`ifndef VX_CONFIG_VH
`define VX_CONFIG_VH

`ifndef __CLOG2
`define __CLOG2(x) ($clog2(x))
`endif

`ifndef __MAX
`define __MAX(a,b) (((a) > (b)) ? (a) : (b))
`endif

`ifndef __MIN
`define __MIN(a,b) (((a) < (b)) ? (a) : (b))
`endif

`ifndef __POW
`define __POW(x,y) ((x) ** (y))
`endif

`ifndef __UP
`define __UP(x) (((x) != 0) ? (x) : 1)
`endif


// --- platform ---
`ifndef VX_CFG_NUM_CLUSTERS
`define VX_CFG_NUM_CLUSTERS 1
`endif

`ifndef VX_CFG_NUM_CORES
`define VX_CFG_NUM_CORES 1
`endif

`ifndef VX_CFG_SOCKET_SIZE
`define VX_CFG_SOCKET_SIZE 1
`endif

`ifndef VX_CFG_RESET_DELAY
`define VX_CFG_RESET_DELAY 8
`endif

`ifndef VX_CFG_ICACHE_DISABLE
`ifndef VX_CFG_ICACHE_ENABLE
`define VX_CFG_ICACHE_ENABLE
`endif
`endif

`ifndef VX_CFG_ICACHE_ENABLED
`ifdef VX_CFG_ICACHE_ENABLE
`define VX_CFG_ICACHE_ENABLED 1
`else
`define VX_CFG_ICACHE_ENABLED 0
`endif
`endif

`ifndef VX_CFG_DCACHE_DISABLE
`ifndef VX_CFG_DCACHE_ENABLE
`define VX_CFG_DCACHE_ENABLE
`endif
`endif

`ifndef VX_CFG_DCACHE_ENABLED
`ifdef VX_CFG_DCACHE_ENABLE
`define VX_CFG_DCACHE_ENABLED 1
`else
`define VX_CFG_DCACHE_ENABLED 0
`endif
`endif

`ifndef VX_CFG_LMEM_DISABLE
`ifndef VX_CFG_LMEM_ENABLE
`define VX_CFG_LMEM_ENABLE
`endif
`endif

`ifndef VX_CFG_LMEM_ENABLED
`ifdef VX_CFG_LMEM_ENABLE
`define VX_CFG_LMEM_ENABLED 1
`else
`define VX_CFG_LMEM_ENABLED 0
`endif
`endif

`ifndef VX_CFG_L2_ENABLED
`ifdef VX_CFG_L2_ENABLE
`define VX_CFG_L2_ENABLED 1
`else
`define VX_CFG_L2_ENABLED 0
`endif
`endif

`ifndef VX_CFG_L3_ENABLED
`ifdef VX_CFG_L3_ENABLE
`define VX_CFG_L3_ENABLED 1
`else
`define VX_CFG_L3_ENABLED 0
`endif
`endif

// --- isa ---
`ifndef VX_CFG_VM_ENABLED
`ifdef VX_CFG_VM_ENABLE
`define VX_CFG_VM_ENABLED 1
`else
`define VX_CFG_VM_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_D_DISABLE
`ifndef VX_CFG_EXT_D_ENABLE
`ifdef VX_CFG_XLEN_64
`define VX_CFG_EXT_D_ENABLE
`endif
`endif
`endif

`ifndef VX_CFG_EXT_D_ENABLED
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_EXT_D_ENABLED 1
`else
`define VX_CFG_EXT_D_ENABLED 0
`endif
`endif

`ifdef VX_CFG_FLEN_32
`undef VX_CFG_FLEN
`define VX_CFG_FLEN 32
`endif
`ifdef VX_CFG_FLEN_64
`undef VX_CFG_FLEN
`define VX_CFG_FLEN 64
`endif

`ifndef VX_CFG_FLEN_32
`ifndef VX_CFG_FLEN_64
`ifndef VX_CFG_FLEN
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FLEN 64
`define VX_CFG_FLEN_64
`else
`define VX_CFG_FLEN 32
`define VX_CFG_FLEN_32
`endif
`endif
`endif
`endif

`ifndef VX_CFG_EXT_M_DISABLE
`ifndef VX_CFG_EXT_M_ENABLE
`define VX_CFG_EXT_M_ENABLE
`endif
`endif

`ifndef VX_CFG_EXT_M_ENABLED
`ifdef VX_CFG_EXT_M_ENABLE
`define VX_CFG_EXT_M_ENABLED 1
`else
`define VX_CFG_EXT_M_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_F_DISABLE
`ifndef VX_CFG_EXT_F_ENABLE
`define VX_CFG_EXT_F_ENABLE
`endif
`endif

`ifndef VX_CFG_EXT_F_ENABLED
`ifdef VX_CFG_EXT_F_ENABLE
`define VX_CFG_EXT_F_ENABLED 1
`else
`define VX_CFG_EXT_F_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_C_ENABLED
`ifdef VX_CFG_EXT_C_ENABLE
`define VX_CFG_EXT_C_ENABLED 1
`else
`define VX_CFG_EXT_C_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_A_ENABLED
`ifdef VX_CFG_EXT_A_ENABLE
`define VX_CFG_EXT_A_ENABLED 1
`else
`define VX_CFG_EXT_A_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_ZICOND_DISABLE
`ifndef VX_CFG_EXT_ZICOND_ENABLE
`define VX_CFG_EXT_ZICOND_ENABLE
`endif
`endif

`ifndef VX_CFG_EXT_ZICOND_ENABLED
`ifdef VX_CFG_EXT_ZICOND_ENABLE
`define VX_CFG_EXT_ZICOND_ENABLED 1
`else
`define VX_CFG_EXT_ZICOND_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_TCU_ENABLED
`ifdef VX_CFG_EXT_TCU_ENABLE
`define VX_CFG_EXT_TCU_ENABLED 1
`else
`define VX_CFG_EXT_TCU_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_DMA_ENABLED
`ifdef VX_CFG_EXT_DMA_ENABLE
`define VX_CFG_EXT_DMA_ENABLED 1
`else
`define VX_CFG_EXT_DMA_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_DXA_ENABLED
`ifdef VX_CFG_EXT_DXA_ENABLE
`define VX_CFG_EXT_DXA_ENABLED 1
`else
`define VX_CFG_EXT_DXA_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_TEX_ENABLED
`ifdef VX_CFG_EXT_TEX_ENABLE
`define VX_CFG_EXT_TEX_ENABLED 1
`else
`define VX_CFG_EXT_TEX_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_RASTER_ENABLED
`ifdef VX_CFG_EXT_RASTER_ENABLE
`define VX_CFG_EXT_RASTER_ENABLED 1
`else
`define VX_CFG_EXT_RASTER_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_OM_ENABLED
`ifdef VX_CFG_EXT_OM_ENABLE
`define VX_CFG_EXT_OM_ENABLED 1
`else
`define VX_CFG_EXT_OM_ENABLED 0
`endif
`endif

`ifndef VX_CFG_EXT_RTU_ENABLED
`ifdef VX_CFG_EXT_RTU_ENABLE
`define VX_CFG_EXT_RTU_ENABLED 1
`else
`define VX_CFG_EXT_RTU_ENABLED 0
`endif
`endif

`ifndef VX_CFG_VLEN
`define VX_CFG_VLEN ((`VX_CFG_XLEN) * (4))
`endif

// --- pipeline ---
`ifndef VX_CFG_NUM_WARPS
`define VX_CFG_NUM_WARPS 4
`endif

`ifndef VX_CFG_NUM_THREADS
`define VX_CFG_NUM_THREADS 4
`endif

`ifndef VX_CFG_NUM_BARRIERS
`define VX_CFG_NUM_BARRIERS 8
`endif

`ifndef VX_CFG_MAX_BAR_EVENTS
`define VX_CFG_MAX_BAR_EVENTS 32
`endif

`ifndef VX_CFG_IBUF_SIZE
`define VX_CFG_IBUF_SIZE 4
`endif

`ifndef VX_CFG_DISPATCH_QUEUE_SIZE
`define VX_CFG_DISPATCH_QUEUE_SIZE 4
`endif

`ifndef VX_CFG_ISSUE_WIDTH
`define VX_CFG_ISSUE_WIDTH `__UP(((`VX_CFG_NUM_WARPS) / (16)))
`endif

`ifndef VX_CFG_SIMD_WIDTH
`define VX_CFG_SIMD_WIDTH `VX_CFG_NUM_THREADS
`endif

`ifndef VX_CFG_NUM_OPCS
`define VX_CFG_NUM_OPCS `__UP(((`VX_CFG_NUM_WARPS) / (((4) * (`VX_CFG_ISSUE_WIDTH)))))
`endif

`ifndef VX_CFG_NUM_GPR_BANKS
`define VX_CFG_NUM_GPR_BANKS 4
`endif

`ifndef VX_CFG_NUM_VGPR_BANKS
`define VX_CFG_NUM_VGPR_BANKS 2
`endif

// --- memory ---
`ifndef VX_CFG_MEM_BLOCK_SIZE
`define VX_CFG_MEM_BLOCK_SIZE 64
`endif

`ifndef VX_CFG_MEM_ADDR_WIDTH
`ifdef VX_CFG_XLEN_64
`define VX_CFG_MEM_ADDR_WIDTH 48
`else
`define VX_CFG_MEM_ADDR_WIDTH 32
`endif
`endif

`ifndef VX_CFG_L1_LINE_SIZE
`define VX_CFG_L1_LINE_SIZE `VX_CFG_MEM_BLOCK_SIZE
`endif

`ifndef VX_CFG_L2_LINE_SIZE
`ifdef VX_CFG_L2_ENABLE
`define VX_CFG_L2_LINE_SIZE ((2) * (`VX_CFG_MEM_BLOCK_SIZE))
`else
`define VX_CFG_L2_LINE_SIZE `VX_CFG_L1_LINE_SIZE
`endif
`endif

`ifndef VX_CFG_L2_SECTOR_SIZE
`ifdef VX_CFG_L2_ENABLE
`define VX_CFG_L2_SECTOR_SIZE `VX_CFG_MEM_BLOCK_SIZE
`else
`define VX_CFG_L2_SECTOR_SIZE `VX_CFG_L1_LINE_SIZE
`endif
`endif

`ifndef VX_CFG_L3_LINE_SIZE
`ifdef VX_CFG_L3_ENABLE
`define VX_CFG_L3_LINE_SIZE ((2) * (`VX_CFG_MEM_BLOCK_SIZE))
`else
`define VX_CFG_L3_LINE_SIZE `VX_CFG_L2_SECTOR_SIZE
`endif
`endif

`ifndef VX_CFG_L3_SECTOR_SIZE
`ifdef VX_CFG_L3_ENABLE
`define VX_CFG_L3_SECTOR_SIZE `VX_CFG_MEM_BLOCK_SIZE
`else
`define VX_CFG_L3_SECTOR_SIZE `VX_CFG_L2_SECTOR_SIZE
`endif
`endif

// --- platform_memory ---
`ifndef VX_CFG_PLATFORM_MEMORY_NUM_BANKS
`define VX_CFG_PLATFORM_MEMORY_NUM_BANKS 2
`endif

`ifndef VX_CFG_PLATFORM_MEMORY_ADDR_WIDTH
`ifdef VX_CFG_XLEN_64
`define VX_CFG_PLATFORM_MEMORY_ADDR_WIDTH 48
`else
`define VX_CFG_PLATFORM_MEMORY_ADDR_WIDTH 32
`endif
`endif

`ifndef VX_CFG_PLATFORM_MEMORY_DATA_SIZE
`define VX_CFG_PLATFORM_MEMORY_DATA_SIZE 64
`endif

`ifndef VX_CFG_PLATFORM_MEMORY_INTERLEAVE
`define VX_CFG_PLATFORM_MEMORY_INTERLEAVE 1
`endif

`ifndef VX_CFG_PLATFORM_MEMORY_PEAK_BW
`define VX_CFG_PLATFORM_MEMORY_PEAK_BW 460000
`endif

`ifndef VX_CFG_PLATFORM_CLOCK_RATE
`define VX_CFG_PLATFORM_CLOCK_RATE 400
`endif

// --- alu ---
`ifndef VX_CFG_NUM_ALU_LANES
`define VX_CFG_NUM_ALU_LANES `VX_CFG_SIMD_WIDTH
`endif

`ifndef VX_CFG_NUM_ALU_BLOCKS
`define VX_CFG_NUM_ALU_BLOCKS 1
`endif

// --- sfu ---
`ifndef VX_CFG_NUM_SFU_LANES
`define VX_CFG_NUM_SFU_LANES `VX_CFG_SIMD_WIDTH
`endif

`ifndef VX_CFG_NUM_SFU_BLOCKS
`define VX_CFG_NUM_SFU_BLOCKS 1
`endif

// --- lsu ---
`ifndef VX_CFG_NUM_LSU_LANES
`define VX_CFG_NUM_LSU_LANES `VX_CFG_SIMD_WIDTH
`endif

`ifndef VX_CFG_NUM_LSU_BLOCKS
`define VX_CFG_NUM_LSU_BLOCKS 1
`endif

`ifndef VX_CFG_LSU_LINE_SIZE
`define VX_CFG_LSU_LINE_SIZE `__MIN(((`VX_CFG_NUM_LSU_LANES) * (((`VX_CFG_XLEN) / (8)))), `VX_CFG_L1_LINE_SIZE)
`endif

`ifndef VX_CFG_LSU_QUEUE_IN_SIZE
`define VX_CFG_LSU_QUEUE_IN_SIZE `__MAX(4, ((2) * (((`VX_CFG_SIMD_WIDTH) / (`VX_CFG_NUM_LSU_LANES)))))
`endif

`ifndef VX_CFG_LSU_PENDING_SIZE
`define VX_CFG_LSU_PENDING_SIZE `__MIN(32, `__MAX(8, ((((2) * (`VX_CFG_NUM_WARPS))) * (((`VX_CFG_SIMD_WIDTH) / (`VX_CFG_NUM_LSU_LANES))))))
`endif

// --- fpu ---
`ifdef VX_CFG_FPU_TYPE_DPI
`undef VX_CFG_FPU_TYPE
`define VX_CFG_FPU_TYPE DPI
`endif
`ifdef VX_CFG_FPU_TYPE_DSP
`undef VX_CFG_FPU_TYPE
`define VX_CFG_FPU_TYPE DSP
`endif
`ifdef VX_CFG_FPU_TYPE_FPNEW
`undef VX_CFG_FPU_TYPE
`define VX_CFG_FPU_TYPE FPNEW
`endif
`ifdef VX_CFG_FPU_TYPE_STD
`undef VX_CFG_FPU_TYPE
`define VX_CFG_FPU_TYPE STD
`endif

`ifndef VX_CFG_FPU_TYPE_DPI
`ifndef VX_CFG_FPU_TYPE_DSP
`ifndef VX_CFG_FPU_TYPE_FPNEW
`ifndef VX_CFG_FPU_TYPE_STD
`ifndef VX_CFG_FPU_TYPE
`ifdef SYNTHESIS
`ifdef ASIC
`define VX_CFG_FPU_TYPE STD
`define VX_CFG_FPU_TYPE_STD
`else
`define VX_CFG_FPU_TYPE DSP
`define VX_CFG_FPU_TYPE_DSP
`endif
`else
`ifdef SV_DPI
`define VX_CFG_FPU_TYPE DPI
`define VX_CFG_FPU_TYPE_DPI
`else
`define VX_CFG_FPU_TYPE STD
`define VX_CFG_FPU_TYPE_STD
`endif
`endif
`endif
`endif
`endif
`endif
`endif

`ifndef VX_CFG_NUM_FPU_LANES
`define VX_CFG_NUM_FPU_LANES `VX_CFG_SIMD_WIDTH
`endif

`ifndef VX_CFG_NUM_FPU_BLOCKS
`define VX_CFG_NUM_FPU_BLOCKS 1
`endif

`ifndef VX_CFG_FPU_QUEUE_SIZE
`define VX_CFG_FPU_QUEUE_SIZE ((2) * (((`VX_CFG_SIMD_WIDTH) / (`VX_CFG_NUM_FPU_LANES))))
`endif

`ifndef VX_CFG_FPU_USE_DSP
`ifdef SYNTHESIS
`ifndef ASIC
`define VX_CFG_FPU_USE_DSP 1
`else
`define VX_CFG_FPU_USE_DSP 0
`endif
`else
`define VX_CFG_FPU_USE_DSP 0
`endif
`endif

`ifndef VX_CFG_FMA_LATENCY
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef VIVADO
`define VX_CFG_FMA_LATENCY 16
`else
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef QUARTUS
`define VX_CFG_FMA_LATENCY 4
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FMA_LATENCY 12
`else
`define VX_CFG_FMA_LATENCY 8
`endif
`endif
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FMA_LATENCY 12
`else
`define VX_CFG_FMA_LATENCY 8
`endif
`endif
`endif
`else
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef QUARTUS
`define VX_CFG_FMA_LATENCY 4
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FMA_LATENCY 12
`else
`define VX_CFG_FMA_LATENCY 8
`endif
`endif
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FMA_LATENCY 12
`else
`define VX_CFG_FMA_LATENCY 8
`endif
`endif
`endif
`endif

`ifndef VX_CFG_FDIV_LATENCY
`ifdef VX_CFG_FPU_TYPE_DPI
`define VX_CFG_FDIV_LATENCY 15
`else
`ifdef VX_CFG_FPU_TYPE_FPNEW
`define VX_CFG_FDIV_LATENCY 16
`else
`ifdef VX_CFG_FPU_TYPE_STD
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FDIV_LATENCY 32
`else
`define VX_CFG_FDIV_LATENCY 17
`endif
`else
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef QUARTUS
`define VX_CFG_FDIV_LATENCY 15
`else
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef VIVADO
`define VX_CFG_FDIV_LATENCY 28
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FDIV_LATENCY 32
`else
`define VX_CFG_FDIV_LATENCY 17
`endif
`endif
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FDIV_LATENCY 32
`else
`define VX_CFG_FDIV_LATENCY 17
`endif
`endif
`endif
`else
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef VIVADO
`define VX_CFG_FDIV_LATENCY 28
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FDIV_LATENCY 32
`else
`define VX_CFG_FDIV_LATENCY 17
`endif
`endif
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FDIV_LATENCY 32
`else
`define VX_CFG_FDIV_LATENCY 17
`endif
`endif
`endif
`endif
`endif
`endif
`endif

`ifndef VX_CFG_FSQRT_LATENCY
`ifdef VX_CFG_FPU_TYPE_DPI
`define VX_CFG_FSQRT_LATENCY 10
`else
`ifdef VX_CFG_FPU_TYPE_FPNEW
`define VX_CFG_FSQRT_LATENCY 16
`else
`ifdef VX_CFG_FPU_TYPE_STD
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FSQRT_LATENCY 32
`else
`define VX_CFG_FSQRT_LATENCY 17
`endif
`else
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef QUARTUS
`define VX_CFG_FSQRT_LATENCY 10
`else
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef VIVADO
`define VX_CFG_FSQRT_LATENCY 28
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FSQRT_LATENCY 32
`else
`define VX_CFG_FSQRT_LATENCY 17
`endif
`endif
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FSQRT_LATENCY 32
`else
`define VX_CFG_FSQRT_LATENCY 17
`endif
`endif
`endif
`else
`ifdef VX_CFG_FPU_TYPE_DSP
`ifdef VIVADO
`define VX_CFG_FSQRT_LATENCY 28
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FSQRT_LATENCY 32
`else
`define VX_CFG_FSQRT_LATENCY 17
`endif
`endif
`else
`ifdef VX_CFG_EXT_D_ENABLE
`define VX_CFG_FSQRT_LATENCY 32
`else
`define VX_CFG_FSQRT_LATENCY 17
`endif
`endif
`endif
`endif
`endif
`endif
`endif

`ifndef VX_CFG_FNCP_LATENCY
`define VX_CFG_FNCP_LATENCY 2
`endif

`ifndef VX_CFG_FCVT_LATENCY
`define VX_CFG_FCVT_LATENCY 5
`endif

`ifndef VX_CFG_FMA_PE_RATIO
`define VX_CFG_FMA_PE_RATIO 1
`endif

`ifndef VX_CFG_FDIV_PE_RATIO
`define VX_CFG_FDIV_PE_RATIO 1
`endif

`ifndef VX_CFG_FSQRT_PE_RATIO
`define VX_CFG_FSQRT_PE_RATIO 1
`endif

`ifndef VX_CFG_FCVT_PE_RATIO
`define VX_CFG_FCVT_PE_RATIO 1
`endif

`ifndef VX_CFG_FNCP_PE_RATIO
`define VX_CFG_FNCP_PE_RATIO 1
`endif

// --- amo ---
`ifndef VX_CFG_AMO_RS_SIZE
`define VX_CFG_AMO_RS_SIZE `__MAX(`VX_CFG_NUM_WARPS, `__UP(((((`VX_CFG_NUM_CORES) * (`VX_CFG_NUM_WARPS))) / (`VX_CFG_L2_NUM_BANKS))))
`endif

// --- vpu ---
`ifndef VX_CFG_NUM_VPU_LANES
`define VX_CFG_NUM_VPU_LANES `VX_CFG_SIMD_WIDTH
`endif

`ifndef VX_CFG_NUM_VPU_BLOCKS
`define VX_CFG_NUM_VPU_BLOCKS 1
`endif

// --- vm ---
`ifndef VX_CFG_TLB_SIZE
`define VX_CFG_TLB_SIZE 32
`endif

`ifndef VX_CFG_VM_PINNED_REGION_SIZE
`define VX_CFG_VM_PINNED_REGION_SIZE 32'h10000000
`endif

// --- l1cache ---
`ifndef VX_CFG_ICACHE_SIZE
`define VX_CFG_ICACHE_SIZE 16384
`endif

`ifndef VX_CFG_ICACHE_NUM_WAYS
`define VX_CFG_ICACHE_NUM_WAYS 4
`endif

`ifndef VX_CFG_ICACHE_REPL_POLICY
`define VX_CFG_ICACHE_REPL_POLICY 1
`endif

`ifndef VX_CFG_ICACHE_MSHR_SIZE
`define VX_CFG_ICACHE_MSHR_SIZE 16
`endif

`ifndef VX_CFG_ICACHE_MRSQ_SIZE
`define VX_CFG_ICACHE_MRSQ_SIZE 0
`endif

`ifndef VX_CFG_ICACHE_MREQ_SIZE
`define VX_CFG_ICACHE_MREQ_SIZE 0
`endif

`ifndef VX_CFG_ICACHE_CRSQ_SIZE
`define VX_CFG_ICACHE_CRSQ_SIZE 0
`endif

`ifndef VX_CFG_ICACHE_MEM_PORTS
`define VX_CFG_ICACHE_MEM_PORTS 1
`endif

`ifndef VX_CFG_ICACHE_LATENCY
`define VX_CFG_ICACHE_LATENCY ((2) + (`__MAX(0, ((`__CLOG2(`VX_CFG_ICACHE_SIZE)) - (`__CLOG2(16384))))))
`endif

`ifndef VX_CFG_DCACHE_SIZE
`define VX_CFG_DCACHE_SIZE 16384
`endif

`ifndef VX_CFG_DCACHE_NUM_WAYS
`define VX_CFG_DCACHE_NUM_WAYS 4
`endif

`ifndef VX_CFG_DCACHE_WORD_SIZE
`define VX_CFG_DCACHE_WORD_SIZE `__MIN(`VX_CFG_L1_LINE_SIZE, `__MIN(`VX_CFG_MEM_BLOCK_SIZE, ((((`VX_CFG_XLEN) / (8))) * (`__POW(2, ((((`__CLOG2(`VX_CFG_NUM_LSU_LANES)) + (1))) / (2)))))))
`endif

`ifndef VX_CFG_DCACHE_WRITEBACK
`define VX_CFG_DCACHE_WRITEBACK (((((((`VX_CFG_L2_ENABLED) == (0))) && (((`VX_CFG_L3_ENABLED) == (0))))) && (((((`VX_CFG_NUM_CORES) == (1))) && (((`VX_CFG_NUM_CLUSTERS) == (1)))))))
`endif

`ifndef VX_CFG_DCACHE_DIRTYBYTES
`define VX_CFG_DCACHE_DIRTYBYTES 0
`endif

`ifndef VX_CFG_DCACHE_REPL_POLICY
`define VX_CFG_DCACHE_REPL_POLICY 1
`endif

`ifndef VX_CFG_DCACHE_MSHR_SIZE
`define VX_CFG_DCACHE_MSHR_SIZE 16
`endif

`ifndef VX_CFG_DCACHE_LINE_SIZE
`define VX_CFG_DCACHE_LINE_SIZE `VX_CFG_L1_LINE_SIZE
`endif

`ifndef VX_CFG_DCACHE_SECTOR_SIZE
`define VX_CFG_DCACHE_SECTOR_SIZE `VX_CFG_L1_LINE_SIZE
`endif

`ifndef VX_CFG_DCACHE_LATENCY
`define VX_CFG_DCACHE_LATENCY ((2) + (`__MAX(0, ((`__CLOG2(`VX_CFG_DCACHE_SIZE)) - (`__CLOG2(16384))))))
`endif

`ifndef VX_CFG_DCACHE_MRSQ_SIZE
`define VX_CFG_DCACHE_MRSQ_SIZE 4
`endif

`ifndef VX_CFG_DCACHE_MREQ_SIZE
`define VX_CFG_DCACHE_MREQ_SIZE 0
`endif

`ifndef VX_CFG_DCACHE_CRSQ_SIZE
`define VX_CFG_DCACHE_CRSQ_SIZE 0
`endif

`ifndef VX_CFG_NUM_ICACHES
`ifdef VX_CFG_ICACHE_ENABLE
`define VX_CFG_NUM_ICACHES `__UP(((`VX_CFG_SOCKET_SIZE) / (4)))
`else
`define VX_CFG_NUM_ICACHES 0
`endif
`endif

`ifndef VX_CFG_NUM_DCACHES
`ifdef VX_CFG_DCACHE_ENABLE
`define VX_CFG_NUM_DCACHES `__UP(((`VX_CFG_SOCKET_SIZE) / (4)))
`else
`define VX_CFG_NUM_DCACHES 0
`endif
`endif

`ifndef VX_CFG_DCACHE_NUM_BANKS
`define VX_CFG_DCACHE_NUM_BANKS `__POW(2, `__CLOG2(`__MIN(DCACHE_NUM_REQS, 16)))
`endif

`ifndef VX_CFG_L1_MEM_PORTS
`ifdef VX_CFG_ICACHE_ENABLE
`define VX_CFG_L1_MEM_PORTS `__MIN(`VX_CFG_DCACHE_NUM_BANKS, `VX_CFG_PLATFORM_MEMORY_NUM_BANKS)
`else
`ifdef VX_CFG_DCACHE_ENABLE
`define VX_CFG_L1_MEM_PORTS `__MIN(`VX_CFG_DCACHE_NUM_BANKS, `VX_CFG_PLATFORM_MEMORY_NUM_BANKS)
`else
`define VX_CFG_L1_MEM_PORTS `__MIN(DCACHE_NUM_REQS, `VX_CFG_PLATFORM_MEMORY_NUM_BANKS)
`endif
`endif
`endif

// --- l2cache ---
`ifndef VX_CFG_L2_SIZE
`define VX_CFG_L2_SIZE 1048576
`endif

`ifndef VX_CFG_L2_NUM_WAYS
`define VX_CFG_L2_NUM_WAYS 8
`endif

`ifndef VX_CFG_L2_WRITEBACK
`define VX_CFG_L2_WRITEBACK (((((((`VX_CFG_L2_ENABLED) == (1))) && (((`VX_CFG_L3_ENABLED) == (0))))) && (((`VX_CFG_NUM_CLUSTERS) == (1)))))
`endif

`ifndef VX_CFG_L2_DIRTYBYTES
`define VX_CFG_L2_DIRTYBYTES 0
`endif

`ifndef VX_CFG_L2_REPL_POLICY
`define VX_CFG_L2_REPL_POLICY 1
`endif

`ifndef VX_CFG_L2_MSHR_SIZE
`define VX_CFG_L2_MSHR_SIZE 16
`endif

`ifndef VX_CFG_L2_LATENCY
`define VX_CFG_L2_LATENCY ((4) + (`__MAX(0, ((`__CLOG2(`VX_CFG_L2_SIZE)) - (`__CLOG2(1048576))))))
`endif

`ifndef VX_CFG_L2_MRSQ_SIZE
`define VX_CFG_L2_MRSQ_SIZE 4
`endif

`ifndef VX_CFG_L2_MREQ_SIZE
`define VX_CFG_L2_MREQ_SIZE 0
`endif

`ifndef VX_CFG_L2_CRSQ_SIZE
`define VX_CFG_L2_CRSQ_SIZE 0
`endif

`ifndef VX_CFG_L2_NUM_BANKS
`define VX_CFG_L2_NUM_BANKS `__POW(2, `__CLOG2(`__MIN(L2_NUM_REQS, 16)))
`endif

`ifndef VX_CFG_L2_MEM_PORTS
`ifdef VX_CFG_L2_ENABLE
`define VX_CFG_L2_MEM_PORTS `__MIN(`VX_CFG_L2_NUM_BANKS, `VX_CFG_PLATFORM_MEMORY_NUM_BANKS)
`else
`define VX_CFG_L2_MEM_PORTS `__MIN(L2_NUM_REQS, `VX_CFG_PLATFORM_MEMORY_NUM_BANKS)
`endif
`endif

// --- l3cache ---
`ifndef VX_CFG_L3_SIZE
`define VX_CFG_L3_SIZE 2097152
`endif

`ifndef VX_CFG_L3_NUM_WAYS
`define VX_CFG_L3_NUM_WAYS 8
`endif

`ifndef VX_CFG_L3_WRITEBACK
`define VX_CFG_L3_WRITEBACK (((`VX_CFG_L3_ENABLED) == (1)))
`endif

`ifndef VX_CFG_L3_DIRTYBYTES
`define VX_CFG_L3_DIRTYBYTES 0
`endif

`ifndef VX_CFG_L3_REPL_POLICY
`define VX_CFG_L3_REPL_POLICY 1
`endif

`ifndef VX_CFG_L3_MSHR_SIZE
`define VX_CFG_L3_MSHR_SIZE 16
`endif

`ifndef VX_CFG_L3_LATENCY
`define VX_CFG_L3_LATENCY ((4) + (`__MAX(0, ((`__CLOG2(`VX_CFG_L3_SIZE)) - (`__CLOG2(2097152))))))
`endif

`ifndef VX_CFG_L3_MRSQ_SIZE
`define VX_CFG_L3_MRSQ_SIZE 4
`endif

`ifndef VX_CFG_L3_MREQ_SIZE
`define VX_CFG_L3_MREQ_SIZE 0
`endif

`ifndef VX_CFG_L3_CRSQ_SIZE
`define VX_CFG_L3_CRSQ_SIZE 0
`endif

`ifndef VX_CFG_L3_NUM_BANKS
`define VX_CFG_L3_NUM_BANKS `__POW(2, `__CLOG2(`__MIN(L3_NUM_REQS, 16)))
`endif

`ifndef VX_CFG_L3_MEM_PORTS
`ifdef VX_CFG_L3_ENABLE
`define VX_CFG_L3_MEM_PORTS `__MIN(`VX_CFG_L3_NUM_BANKS, `VX_CFG_PLATFORM_MEMORY_NUM_BANKS)
`else
`define VX_CFG_L3_MEM_PORTS `__MIN(L3_NUM_REQS, `VX_CFG_PLATFORM_MEMORY_NUM_BANKS)
`endif
`endif

// --- lmem ---
`ifndef VX_CFG_LMEM_LOG_SIZE
`define VX_CFG_LMEM_LOG_SIZE 14
`endif

`ifndef VX_CFG_LMEM_NUM_BANKS
`define VX_CFG_LMEM_NUM_BANKS `VX_CFG_NUM_LSU_LANES
`endif

// --- tcu ---
`ifdef VX_CFG_TCU_TYPE_DPI
`undef VX_CFG_TCU_TYPE
`define VX_CFG_TCU_TYPE DPI
`endif
`ifdef VX_CFG_TCU_TYPE_DSP
`undef VX_CFG_TCU_TYPE
`define VX_CFG_TCU_TYPE DSP
`endif
`ifdef VX_CFG_TCU_TYPE_BHF
`undef VX_CFG_TCU_TYPE
`define VX_CFG_TCU_TYPE BHF
`endif
`ifdef VX_CFG_TCU_TYPE_TFR
`undef VX_CFG_TCU_TYPE
`define VX_CFG_TCU_TYPE TFR
`endif
`ifdef VX_CFG_TCU_TYPE_FPNEW
`undef VX_CFG_TCU_TYPE
`define VX_CFG_TCU_TYPE FPNEW
`endif

`ifndef VX_CFG_TCU_TYPE_DPI
`ifndef VX_CFG_TCU_TYPE_DSP
`ifndef VX_CFG_TCU_TYPE_BHF
`ifndef VX_CFG_TCU_TYPE_TFR
`ifndef VX_CFG_TCU_TYPE_FPNEW
`ifndef VX_CFG_TCU_TYPE
`define VX_CFG_TCU_TYPE TFR
`define VX_CFG_TCU_TYPE_TFR
`endif
`endif
`endif
`endif
`endif
`endif

`ifndef VX_CFG_NUM_TCU_LANES
`define VX_CFG_NUM_TCU_LANES `VX_CFG_NUM_THREADS
`endif

`ifndef VX_CFG_NUM_TCU_BLOCKS
`define VX_CFG_NUM_TCU_BLOCKS `VX_CFG_ISSUE_WIDTH
`endif

`ifndef VX_CFG_TCU_USE_DSP
`ifdef SYNTHESIS
`ifndef ASIC
`define VX_CFG_TCU_USE_DSP 1
`else
`define VX_CFG_TCU_USE_DSP 0
`endif
`else
`define VX_CFG_TCU_USE_DSP 0
`endif
`endif

`ifndef VX_CFG_TCU_TF32_ENABLED
`ifdef VX_CFG_TCU_TF32_ENABLE
`define VX_CFG_TCU_TF32_ENABLED 1
`else
`define VX_CFG_TCU_TF32_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_FP16_DISABLE
`ifndef VX_CFG_TCU_FP16_ENABLE
`define VX_CFG_TCU_FP16_ENABLE
`endif
`endif

`ifndef VX_CFG_TCU_FP16_ENABLED
`ifdef VX_CFG_TCU_FP16_ENABLE
`define VX_CFG_TCU_FP16_ENABLED 1
`else
`define VX_CFG_TCU_FP16_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_FP8_ENABLED
`ifdef VX_CFG_TCU_FP8_ENABLE
`define VX_CFG_TCU_FP8_ENABLED 1
`else
`define VX_CFG_TCU_FP8_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_FP4_ENABLED
`ifdef VX_CFG_TCU_FP4_ENABLE
`define VX_CFG_TCU_FP4_ENABLED 1
`else
`define VX_CFG_TCU_FP4_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_INT8_ENABLED
`ifdef VX_CFG_TCU_INT8_ENABLE
`define VX_CFG_TCU_INT8_ENABLED 1
`else
`define VX_CFG_TCU_INT8_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_INT4_ENABLED
`ifdef VX_CFG_TCU_INT4_ENABLE
`define VX_CFG_TCU_INT4_ENABLED 1
`else
`define VX_CFG_TCU_INT4_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_MX_ENABLED
`ifdef VX_CFG_TCU_MX_ENABLE
`define VX_CFG_TCU_MX_ENABLED 1
`else
`define VX_CFG_TCU_MX_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_MXFP4_ENABLED
`ifdef VX_CFG_TCU_MXFP4_ENABLE
`define VX_CFG_TCU_MXFP4_ENABLED 1
`else
`define VX_CFG_TCU_MXFP4_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_NVFP4_ENABLED
`ifdef VX_CFG_TCU_NVFP4_ENABLE
`define VX_CFG_TCU_NVFP4_ENABLED 1
`else
`define VX_CFG_TCU_NVFP4_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_SPARSE_ENABLED
`ifdef VX_CFG_TCU_SPARSE_ENABLE
`define VX_CFG_TCU_SPARSE_ENABLED 1
`else
`define VX_CFG_TCU_SPARSE_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_DSM_ENABLED
`ifdef VX_CFG_TCU_DSM_ENABLE
`define VX_CFG_TCU_DSM_ENABLED 1
`else
`define VX_CFG_TCU_DSM_ENABLED 0
`endif
`endif

`ifndef VX_CFG_TCU_WGMMA_ENABLED
`ifdef VX_CFG_TCU_WGMMA_ENABLE
`define VX_CFG_TCU_WGMMA_ENABLED 1
`else
`define VX_CFG_TCU_WGMMA_ENABLED 0
`endif
`endif

// --- dxa ---
`ifndef VX_CFG_NUM_DXA_CORES
`define VX_CFG_NUM_DXA_CORES `__MAX(1, `__UP(((`VX_CFG_NUM_CORES) / (8))))
`endif

`ifndef VX_CFG_DXA_MEM_PORTS
`define VX_CFG_DXA_MEM_PORTS `__MIN(`VX_CFG_NUM_DXA_CORES, ((`__UP(((`VX_CFG_NUM_CORES) / (`VX_CFG_SOCKET_SIZE)))) * (`VX_CFG_L1_MEM_PORTS)))
`endif

`ifndef VX_CFG_DXA_QUEUE_SIZE
`define VX_CFG_DXA_QUEUE_SIZE 16
`endif

`ifndef VX_CFG_DXA_MAX_INFLIGHT
`define VX_CFG_DXA_MAX_INFLIGHT 8
`endif

// --- rtu ---
`ifndef VX_CFG_NUM_RTU_CORES
`define VX_CFG_NUM_RTU_CORES `__MAX(1, `__UP(((`VX_CFG_NUM_CORES) / (4))))
`endif

`ifndef VX_CFG_RTU_BVH_WIDTH
`define VX_CFG_RTU_BVH_WIDTH 4
`endif

`ifndef VX_CFG_RTU_TLAS_ENABLED
`ifdef VX_CFG_RTU_TLAS_ENABLE
`define VX_CFG_RTU_TLAS_ENABLED 1
`else
`define VX_CFG_RTU_TLAS_ENABLED 0
`endif
`endif

`ifndef VX_CFG_RTU_STACK_DEPTH
`define VX_CFG_RTU_STACK_DEPTH 16
`endif

`ifndef VX_CFG_RTU_RECIP_DSP_SEED
`define VX_CFG_RTU_RECIP_DSP_SEED 0
`endif

`ifndef VX_CFG_RTU_USE_DSP
`ifdef SYNTHESIS
`ifndef ASIC
`define VX_CFG_RTU_USE_DSP 1
`else
`define VX_CFG_RTU_USE_DSP 0
`endif
`else
`define VX_CFG_RTU_USE_DSP 0
`endif
`endif

`ifndef VX_CFG_RTU_FDIV_LATENCY
`ifdef VIVADO
`define VX_CFG_RTU_FDIV_LATENCY 28
`else
`ifdef QUARTUS
`define VX_CFG_RTU_FDIV_LATENCY 15
`else
`define VX_CFG_RTU_FDIV_LATENCY 17
`endif
`endif
`endif

`ifndef VX_CFG_RTU_NUM_CTX
`define VX_CFG_RTU_NUM_CTX `VX_CFG_NUM_THREADS
`endif

`ifndef VX_CFG_NUM_RTU_BLOCKS
`define VX_CFG_NUM_RTU_BLOCKS 2
`endif

// --- tex ---
`ifndef VX_CFG_NUM_TEX_CORES
`define VX_CFG_NUM_TEX_CORES `__MAX(1, `__UP(((`VX_CFG_NUM_CORES) / (8))))
`endif

`ifndef VX_CFG_TEX_REQ_QUEUE_SIZE
`define VX_CFG_TEX_REQ_QUEUE_SIZE `__MAX(2, ((2) * (`__UP(((`VX_CFG_NUM_THREADS) / (`VX_CFG_NUM_SFU_LANES))))))
`endif

`ifndef VX_CFG_TEX_MEM_QUEUE_SIZE
`define VX_CFG_TEX_MEM_QUEUE_SIZE `VX_CFG_TEX_REQ_QUEUE_SIZE
`endif

// --- raster ---
`ifndef VX_CFG_NUM_RASTER_CORES
`define VX_CFG_NUM_RASTER_CORES `__MAX(1, `__UP(((`VX_CFG_NUM_CORES) / (16))))
`endif

`ifndef VX_CFG_RASTER_NUM_SLICES
`define VX_CFG_RASTER_NUM_SLICES 1
`endif

`ifndef VX_CFG_RASTER_TILE_LOG_SIZE
`define VX_CFG_RASTER_TILE_LOG_SIZE 5
`endif

`ifndef VX_CFG_RASTER_BIN_LOG_SIZE
`define VX_CFG_RASTER_BIN_LOG_SIZE 7
`endif

`ifndef VX_CFG_RASTER_BLOCK_LOG_SIZE
`define VX_CFG_RASTER_BLOCK_LOG_SIZE 2
`endif

`ifndef VX_CFG_RASTER_MEM_FIFO_DEPTH
`define VX_CFG_RASTER_MEM_FIFO_DEPTH 8
`endif

`ifndef VX_CFG_RASTER_QUAD_FIFO_DEPTH
`define VX_CFG_RASTER_QUAD_FIFO_DEPTH 32
`endif

`ifndef VX_CFG_RASTER_MEM_QUEUE_SIZE
`define VX_CFG_RASTER_MEM_QUEUE_SIZE 4
`endif

`ifndef VX_CFG_RASTER_EARLYZ_ENABLED
`ifdef VX_CFG_RASTER_EARLYZ_ENABLE
`define VX_CFG_RASTER_EARLYZ_ENABLED 1
`else
`define VX_CFG_RASTER_EARLYZ_ENABLED 0
`endif
`endif

// --- om ---
`ifndef VX_CFG_NUM_OM_CORES
`define VX_CFG_NUM_OM_CORES `__MAX(1, `__UP(((`VX_CFG_NUM_CORES) / (8))))
`endif

`ifndef VX_CFG_OM_MEM_QUEUE_SIZE
`define VX_CFG_OM_MEM_QUEUE_SIZE 4
`endif

// --- tcache ---
`ifndef VX_CFG_TCACHE_SIZE
`define VX_CFG_TCACHE_SIZE 8192
`endif

`ifndef VX_CFG_TCACHE_NUM_BANKS
`define VX_CFG_TCACHE_NUM_BANKS 1
`endif

`ifndef VX_CFG_TCACHE_NUM_WAYS
`define VX_CFG_TCACHE_NUM_WAYS 2
`endif

`ifndef VX_CFG_TCACHE_CRSQ_SIZE
`define VX_CFG_TCACHE_CRSQ_SIZE 0
`endif

`ifndef VX_CFG_TCACHE_MSHR_SIZE
`define VX_CFG_TCACHE_MSHR_SIZE 16
`endif

`ifndef VX_CFG_TCACHE_MRSQ_SIZE
`define VX_CFG_TCACHE_MRSQ_SIZE 0
`endif

`ifndef VX_CFG_TCACHE_MREQ_SIZE
`define VX_CFG_TCACHE_MREQ_SIZE 0
`endif

`ifndef VX_CFG_NUM_TCACHES
`define VX_CFG_NUM_TCACHES `__MAX(1, `__UP(((`VX_CFG_NUM_TEX_CORES) / (4))))
`endif

// --- rcache ---
`ifndef VX_CFG_RCACHE_SIZE
`define VX_CFG_RCACHE_SIZE 4096
`endif

`ifndef VX_CFG_RCACHE_NUM_BANKS
`define VX_CFG_RCACHE_NUM_BANKS 1
`endif

`ifndef VX_CFG_RCACHE_NUM_WAYS
`define VX_CFG_RCACHE_NUM_WAYS 2
`endif

`ifndef VX_CFG_RCACHE_CRSQ_SIZE
`define VX_CFG_RCACHE_CRSQ_SIZE 0
`endif

`ifndef VX_CFG_RCACHE_MSHR_SIZE
`define VX_CFG_RCACHE_MSHR_SIZE 16
`endif

`ifndef VX_CFG_RCACHE_MRSQ_SIZE
`define VX_CFG_RCACHE_MRSQ_SIZE 0
`endif

`ifndef VX_CFG_RCACHE_MREQ_SIZE
`define VX_CFG_RCACHE_MREQ_SIZE 0
`endif

`ifndef VX_CFG_NUM_RCACHES
`define VX_CFG_NUM_RCACHES `__MAX(1, `__UP(((`VX_CFG_NUM_RASTER_CORES) / (4))))
`endif

// --- rtcache ---
`ifndef VX_CFG_RTCACHE_SIZE
`define VX_CFG_RTCACHE_SIZE 8192
`endif

`ifndef VX_CFG_RTCACHE_NUM_BANKS
`define VX_CFG_RTCACHE_NUM_BANKS 1
`endif

`ifndef VX_CFG_RTCACHE_NUM_WAYS
`define VX_CFG_RTCACHE_NUM_WAYS 2
`endif

`ifndef VX_CFG_RTCACHE_CRSQ_SIZE
`define VX_CFG_RTCACHE_CRSQ_SIZE 2
`endif

`ifndef VX_CFG_RTCACHE_MSHR_SIZE
`define VX_CFG_RTCACHE_MSHR_SIZE 16
`endif

`ifndef VX_CFG_RTCACHE_MREQ_SIZE
`define VX_CFG_RTCACHE_MREQ_SIZE 4
`endif

`ifndef VX_CFG_RTCACHE_MRSQ_SIZE
`define VX_CFG_RTCACHE_MRSQ_SIZE 0
`endif

`ifndef VX_CFG_NUM_RTCACHES
`define VX_CFG_NUM_RTCACHES `__MAX(1, `__UP(((`VX_CFG_NUM_RTU_CORES) / (4))))
`endif

// --- ocache ---
`ifndef VX_CFG_OCACHE_SIZE
`define VX_CFG_OCACHE_SIZE 16384
`endif

`ifndef VX_CFG_OCACHE_NUM_BANKS
`define VX_CFG_OCACHE_NUM_BANKS 1
`endif

`ifndef VX_CFG_OCACHE_NUM_WAYS
`define VX_CFG_OCACHE_NUM_WAYS 2
`endif

`ifndef VX_CFG_OCACHE_CRSQ_SIZE
`define VX_CFG_OCACHE_CRSQ_SIZE 0
`endif

`ifndef VX_CFG_OCACHE_MSHR_SIZE
`define VX_CFG_OCACHE_MSHR_SIZE 16
`endif

`ifndef VX_CFG_OCACHE_MRSQ_SIZE
`define VX_CFG_OCACHE_MRSQ_SIZE 0
`endif

`ifndef VX_CFG_OCACHE_MREQ_SIZE
`define VX_CFG_OCACHE_MREQ_SIZE 0
`endif

`ifndef VX_CFG_NUM_OCACHES
`define VX_CFG_NUM_OCACHES `__MAX(1, `__UP(((`VX_CFG_NUM_OM_CORES) / (4))))
`endif

// --- isa_signatures ---
`ifndef VX_CFG_MISA_STD
`define VX_CFG_MISA_STD ((((((((((((((((((((((((((((((((((((((((((((((((((((`VX_CFG_EXT_A_ENABLED) << (0))) | (((0) << (1))))) | (((`VX_CFG_EXT_C_ENABLED) << (2))))) | (((`VX_CFG_EXT_D_ENABLED) << (3))))) | (((0) << (4))))) | (((`VX_CFG_EXT_F_ENABLED) << (5))))) | (((0) << (6))))) | (((0) << (7))))) | (((1) << (8))))) | (((0) << (9))))) | (((0) << (10))))) | (((0) << (11))))) | (((`VX_CFG_EXT_M_ENABLED) << (12))))) | (((0) << (13))))) | (((0) << (14))))) | (((0) << (15))))) | (((0) << (16))))) | (((0) << (17))))) | (((0) << (18))))) | (((0) << (19))))) | (((1) << (20))))) | (((0) << (21))))) | (((0) << (22))))) | (((1) << (23))))) | (((0) << (24))))) | (((0) << (25))))
`endif

`ifndef VX_CFG_MISA_EXT
`define VX_CFG_MISA_EXT ((((((((((((((((((((((((`VX_CFG_ICACHE_ENABLED) << (0))) | (((`VX_CFG_DCACHE_ENABLED) << (1))))) | (((`VX_CFG_L2_ENABLED) << (2))))) | (((`VX_CFG_L3_ENABLED) << (3))))) | (((`VX_CFG_LMEM_ENABLED) << (4))))) | (((`VX_CFG_EXT_ZICOND_ENABLED) << (5))))) | (((`VX_CFG_EXT_TCU_ENABLED) << (9))))) | (((`VX_CFG_EXT_DXA_ENABLED) << (10))))) | (((`VX_CFG_EXT_TEX_ENABLED) << (6))))) | (((`VX_CFG_EXT_RASTER_ENABLED) << (7))))) | (((`VX_CFG_EXT_OM_ENABLED) << (8))))) | (((`VX_CFG_EXT_RTU_ENABLED) << (11))))
`endif

// --- debug ---
`ifndef VX_DBG_STALL_TIMEOUT
`define VX_DBG_STALL_TIMEOUT ((100000) * (((1) << (((`VX_CFG_L2_ENABLED) + (`VX_CFG_L3_ENABLED))))))
`endif

`ifndef VX_DBG_DEBUG_LEVEL
`define VX_DBG_DEBUG_LEVEL 3
`endif

`endif  // VX_CONFIG_VH
